# tell Cargo to build targeting wasm32
[build]
target = "wasm32-unknown-unknown"

# compiler adjustments for wasm-bindgen-rayon
[target.wasm32-unknown-unknown]
rustflags = [
              # failed attempts to silence warnings for using unstable compiler options for atomics, issue persists
              # "-Z", "unstable-options",
              # "-A", "unstable_features",
              "-C", "target-feature=+atomics,+bulk-memory,+mutable-globals",
            ]

[unstable]
build-std = ["panic_abort", "std"]
