name: Build Client iOS

on:
  workflow_call:
    inputs:
      web-prover-circuits-cache-key:
        required: true
        type: string

jobs:
  build:
    name: build client ios
    runs-on: macos-latest
    env:
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/setup-rust-macos
        with:
          rust-cache-key: client_ios

      - name: Install WASM Rust components
        run: |
          rustup target add aarch64-apple-ios-sim --toolchain nightly
          rustup target add aarch64-apple-ios --toolchain nightly

      - name: Fetch web-prover-circuits cache
        uses: actions/cache/restore@v4
        with:
          path: proofs/web_proof_circuits
          key: ${{ inputs.web-prover-circuits-cache-key }}

      - name: Build iOS lib
        run: |
          export RUSTFLAGS="-C panic=unwind"

          rm -rf target/{sim,device}
          rm -rf target/PlutoProver.xcframework
          mkdir -p target/{sim,device}/headers

          cargo build -p client_ios --release --target aarch64-apple-ios-sim # builds target/aarch64-apple-ios-sim/release/libclient_ios.a
          cbindgen --lang c --crate client_ios --output target/sim/headers/Prover.h
          mv target/aarch64-apple-ios-sim/release/libclient_ios.a target/sim/libProver.a

          cargo build -p client_ios --release --target aarch64-apple-ios # builds target/aarch64-apple-ios/release/libclient_ios.a
          cbindgen --lang c --crate client_ios --output target/device/headers/Prover.h
          mv target/aarch64-apple-ios/release/libclient_ios.a target/device/libProver.a

          xcodebuild -create-xcframework \
            -library "target/sim/libProver.a" \
            -headers target/sim/headers \
            -library "target/device/libProver.a" \
            -headers target/device/headers \
            -output target/PlutoProver.xcframework

      - uses: actions/upload-artifact@v4
        with:
          # TODO rename to client?
          name: "PlutoProver.xcframework"
          path: "target/PlutoProver.xcframework"
          retention-days: 7
          if-no-files-found: "error"

      - name: Cleanup to prevent caching of assets
        run: |
          rm -rf target/{sim,device}
          rm -rf target/PlutoProver.xcframework
